paths:
  # Change the path to the directory to store outputs
  out_dir: "/absolute/path/to/outputs"

# Script settings
settings:
  required_args: 5
  normalize_graphs: 0

# Messages
messages:
  gc_content: "--- calculating GC content"
  one2one: "--- running one2one for {org1_short}-{org2_short}"
  maf_join: "--- maf-join the two .maf files"
  make_dir: "--- making {dir_path}"
  file_exists: "{file_name} already exists"
  dinuc_tsv: "--- generating dinuc .tsv files"

# Error messages
errors:
  arg_count: "You need {arg_num} arguments"
  usage: |
    Usage: ./trisbst_3spc.sh <date> <org1.fa> <org2.fa> <org3.fa> <org1.gff|NO_GFF_FILE> [--out-dir /absolute/path/to/outputs]
    - org1 should be the outgroup.
    - All FASTA file paths must be absolute paths.
    - If org1 annotation (GFF file) is unavailable, enter "NO_GFF_FILE"; otherwise, provide the GFF file path.
    - The `--out-dir` flag is optional. If not provided, the outputs will be stored in the directory specified in `scripts/last/sbst_config.yaml`.
# Options
options:
  checkInnerGroupIdt:
    description: "Run inner group substitution percent identity check"
    enabled_message: "Running inner group substitution percent identity check..."
    completed_message: "Inner group substitution percent identity check completed"

# File patterns and suffixes
patterns:
  gc_content: "{org_short}_gcContent_{date}.out"
  sbst_ratio: "sbstRatio_{date}.out"
  sbst_ratio_maflinked: "sbstRatio_{date}_maflinked.out"
  many2one: "{org1_short}2{org2_short}_many2one_{date}.maf"
  one2one: "{org1_short}2{org2_short}_one2one_{date}.maf"
  train: "{org1_short}2{org2_short}_{date}.train"
  maflinked: "{org1_short}2{org2_short}_one2one_{date}_maflinked.maf"
  joined: "{org1_short}_{org2_short}_{org3_short}_{date}.maf"
  joined_maflinked: "{org1_short}_{org2_short}_{org3_short}_{date}_maflinked.maf"
  joined_ncds: "{org1_short}_{org2_short}_{org3_short}_{date}_ncds.maf"
  joined_maflinked_ncds: "{org1_short}_{org2_short}_{org3_short}_{date}_maflinked_ncds.maf"
  tsv: "{org_short}_{date}.tsv"
  tsv_maflinked: "{org_short}_{date}_maflinked.tsv"
  tsv_errprb: "{org_short}_{date}_errprb.tsv"
  tsv_maflinked_errprb: "{org_short}_{date}_maflinked_errprb.tsv"
  tsv_ncds: "{org_short}_{date}_ncds.tsv"
  tsv_maflinked_ncds: "{org_short}_{date}_maflinked_ncds.tsv"
  dinuc_tsv: "{org_short}_{date}_dinuc.tsv"
  dinuc_maflinked_tsv: "{org_short}_{date}_maflinked_dinuc.tsv"
  dinuc_tsv_ncds: "{org_short}_{date}_dinuc_ncds.tsv"
  dinuc_maflinked_tsv_ncds: "{org_short}_{date}_maflinked_dinuc_ncds.tsv"
  bed: "{org_short}_{date}.bed"
  bed_maflinked: "{org_short}_{date}_maflinked.bed"

  graph:
    out: "{org_short}_{date}.out"
    sbst: "{org_short}_{date}_sbstCount.out"
    ori: "{org_short}_{date}_oriCount.out"
  graph_maflinked:
    out: "{org_short}_{date}_maflinked.out"
    sbst: "{org_short}_{date}_maflinked_sbstCount.out"
    ori: "{org_short}_{date}_maflinked_oriCount.out"
  graph_errprb:
    out: "{org_short}_{date}_errprb.out"
    sbst: "{org_short}_{date}_errprb_sbstCount.out"
    ori: "{org_short}_{date}_errprb_oriCount.out"
  graph_maflinked_errprb:
    out: "{org_short}_{date}_maflinked_errprb.out"
    sbst: "{org_short}_{date}_maflinked_errprb_sbstCount.out"
    ori: "{org_short}_{date}_maflinked_errprb_oriCount.out"
